/**
 * PR Comment formatter
 *
 * Posts (or updates) a single DeployGuard comment on the pull request.
 * Uses a hidden HTML marker to find and replace an existing comment rather
 * than posting duplicates on every push.
 */

import type { GateResult, ScanResult, SeverityLevel } from "./types";

const COMMENT_MARKER = "<!-- deployguard-scan-comment -->";

const SEV_EMOJI: Record<SeverityLevel, string> = {
  critical: "🔴", high: "🟠", medium: "🟡", low: "🔵", info: "⚪",
};

const REC_EMOJI: Record<string, string> = {
  deploy: "✅", review: "⚠️", block: "🚫",
};

// Type-erased GitHub octokit + context shapes so the file compiles without
// importing @actions/github at the type level (keeps the plan scaffold simpler).
type Octokit = {
  rest: {
    issues: {
      listComments(args: object):  Promise<{ data: Array<{ id: number; body?: string }> }>;
      createComment(args: object): Promise<unknown>;
      updateComment(args: object): Promise<unknown>;
    };
  };
};
type Context = {
  repo:    { owner: string; repo: string };
  payload: { pull_request?: { number: number } };
};

export async function postPRComment(
  octokit: Octokit,
  context: Context,
  scan:    ScanResult,
  gate:    GateResult,
): Promise<void> {
  const pr = context.payload.pull_request;
  if (!pr) return;

  const body = buildCommentBody(scan, gate);
  const { owner, repo } = context.repo;

  // Look for an existing DeployGuard comment to update instead of posting a new one
  const comments = await octokit.rest.issues.listComments({
    owner, repo, issue_number: pr.number, per_page: 100,
  });

  const existing = comments.data.find(c => c.body?.includes(COMMENT_MARKER));

  if (existing) {
    await octokit.rest.issues.updateComment({ owner, repo, comment_id: existing.id, body });
  } else {
    await octokit.rest.issues.createComment({ owner, repo, issue_number: pr.number, body });
  }
}

// ── Comment body builder ──────────────────────────────────────────────────────

function buildCommentBody(scan: ScanResult, gate: GateResult): string {
  const { score, summary, findings } = scan;
  const rec    = score.recommendation;
  const active = findings.filter(f => !f.falsePositive);

  const header = gate.passed
    ? `## ${REC_EMOJI[rec]} DeployGuard — ${rec.toUpperCase()}`
    : `## 🚫 DeployGuard — Deployment Blocked`;

  const scoreRow = `**Score:** ${score.overall}/100 &nbsp;·&nbsp; **Security:** ${score.security} &nbsp;·&nbsp; **Reliability:** ${score.reliability} &nbsp;·&nbsp; **Compliance:** ${score.compliance}`;

  const summaryTable = [
    "| Severity | Count |",
    "|---|---|",
    summary.critical > 0 ? `| ${SEV_EMOJI.critical} Critical | **${summary.critical}** |` : null,
    summary.high     > 0 ? `| ${SEV_EMOJI.high} High | **${summary.high}** |`             : null,
    summary.medium   > 0 ? `| ${SEV_EMOJI.medium} Medium | ${summary.medium} |`           : null,
    summary.low      > 0 ? `| ${SEV_EMOJI.low} Low | ${summary.low} |`                   : null,
    summary.info     > 0 ? `| ${SEV_EMOJI.info} Info | ${summary.info} |`                : null,
    `| ✅ Passed | ${summary.passed} |`,
  ].filter(Boolean).join("\n");

  // Top findings (up to 5, sorted by severity)
  const topFindings = active
    .sort((a, b) => {
      const order: Record<SeverityLevel, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
      return order[a.severity] - order[b.severity];
    })
    .slice(0, 5);

  const findingsSection = topFindings.length > 0
    ? [
        "### Top Findings",
        "",
        topFindings.map(f => [
          `**${SEV_EMOJI[f.severity]} [${f.ruleId}] ${f.title}**`,
          f.filePath ? `\`${f.filePath}:${f.lineNumber ?? 0}\`` : "",
          `> ${f.remediation ?? f.description}`,
        ].filter(Boolean).join("  \n")).join("\n\n"),
        active.length > 5 ? `\n_…and ${active.length - 5} more. [View full report](#)._` : "",
      ].join("\n")
    : "_No active findings._";

  const gateSection = gate.checks.map(c =>
    `${c.passed ? "✓" : "✗"} **${c.name}:** ${c.detail}`
  ).join("  \n");

  return [
    COMMENT_MARKER,
    header,
    "",
    scoreRow,
    "",
    summaryTable,
    "",
    "---",
    "",
    findingsSection,
    "",
    "---",
    "",
    "### Gate Checks",
    "",
    gateSection,
    "",
    `<sub>Generated by [DeployGuard](https://deployguard.dev) · commit \`${process.env.GITHUB_SHA?.slice(0, 7) ?? "unknown"}\`</sub>`,
  ].join("\n");
}
