import type { Finding, ScanResult, DeployScore, ScanSummary, DynamicTestEntry } from "@/types";

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "f-001",
    ruleId: "SEC-001",
    title: "Hardcoded AWS secret key",
    description: "An AWS secret access key was detected hardcoded in source code. This credential could grant unauthorized access to cloud resources if the repository is exposed.",
    severity: "critical",
    category: "secrets",
    filePath: "src/config/aws.ts",
    lineNumber: 14,
    snippet: 'const AWS_SECRET = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"',
    remediation: "Remove the hardcoded credential immediately, rotate the AWS key, and move secrets to AWS Secrets Manager or environment variables.",
    references: ["https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_credentials"],
    falsePositive: false,
  },
  {
    id: "f-002",
    ruleId: "SEC-002",
    title: "SQL injection via string concatenation",
    description: "User input is concatenated directly into a SQL query string without sanitization, creating a SQL injection vulnerability.",
    severity: "high",
    category: "security",
    filePath: "src/api/users/route.ts",
    lineNumber: 47,
    snippet: 'const query = `SELECT * FROM users WHERE email = \'${req.body.email}\'`',
    remediation: "Use parameterized queries or Prisma's type-safe query builder. Never interpolate user input directly into SQL strings.",
    references: ["https://owasp.org/www-community/attacks/SQL_Injection"],
    falsePositive: false,
  },
  {
    id: "f-003",
    ruleId: "SEC-007",
    title: "Missing authentication on admin endpoint",
    description: "The /api/admin/users endpoint does not verify authentication tokens before processing requests, allowing unauthenticated access.",
    severity: "high",
    category: "security",
    filePath: "src/api/admin/users/route.ts",
    lineNumber: 8,
    snippet: "export async function DELETE(req: Request) {\n  const { userId } = await req.json()\n  // no auth check",
    remediation: "Add middleware to verify the request contains a valid admin JWT before processing any admin operations.",
    references: ["https://owasp.org/Top10/A01_2021-Broken_Access_Control/"],
    falsePositive: false,
  },
  {
    id: "f-004",
    ruleId: "DEP-003",
    title: "Critical vulnerability in jsonwebtoken@8.5.1",
    description: "jsonwebtoken ≤8.5.1 is vulnerable to CVE-2022-23539: algorithms confusion allows forging tokens. Upgrade to ≥9.0.0.",
    severity: "high",
    category: "dependency",
    filePath: "package.json",
    lineNumber: 23,
    snippet: '"jsonwebtoken": "^8.5.1"',
    remediation: "Run `npm install jsonwebtoken@latest` and update any token verification calls to pass the `algorithms` option explicitly.",
    references: ["https://nvd.nist.gov/vuln/detail/CVE-2022-23539"],
    falsePositive: false,
  },
  {
    id: "f-005",
    ruleId: "CFG-002",
    title: "CORS configured with wildcard origin",
    description: "Access-Control-Allow-Origin is set to '*', permitting any website to make authenticated requests to this API.",
    severity: "medium",
    category: "configuration",
    filePath: "src/middleware.ts",
    lineNumber: 31,
    snippet: 'res.setHeader("Access-Control-Allow-Origin", "*")',
    remediation: "Restrict CORS to known origins by setting an explicit allowlist of trusted domains.",
    references: ["https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS"],
    falsePositive: false,
  },
  {
    id: "f-006",
    ruleId: "REL-004",
    title: "Unhandled promise rejection in webhook handler",
    description: "The Stripe webhook handler performs async operations without try/catch, which will cause unhandled rejections and crash the process in Node ≥15.",
    severity: "medium",
    category: "reliability",
    filePath: "src/api/webhooks/stripe/route.ts",
    lineNumber: 19,
    snippet: "export async function POST(req: Request) {\n  const event = await stripe.webhooks.constructEvent(...)",
    remediation: "Wrap the handler body in try/catch and return an appropriate error response with status 500.",
    references: [],
    falsePositive: false,
  },
  {
    id: "f-007",
    ruleId: "PERF-001",
    title: "N+1 query pattern in user listing",
    description: "For each user record, a separate database query fetches the associated organization. This creates N+1 queries that will degrade under load.",
    severity: "medium",
    category: "performance",
    filePath: "src/lib/users.ts",
    lineNumber: 58,
    snippet: "const users = await prisma.user.findMany()\nconst orgs = await Promise.all(users.map(u => prisma.org.findUnique({where: {id: u.orgId}})))",
    remediation: "Use Prisma's `include` option to fetch users with their organizations in a single query.",
    references: [],
    falsePositive: false,
  },
  {
    id: "f-008",
    ruleId: "CFG-005",
    title: "Rate limiting absent on authentication endpoint",
    description: "The /api/auth/login endpoint has no rate limiting, making it vulnerable to brute-force credential attacks.",
    severity: "medium",
    category: "configuration",
    filePath: "src/api/auth/login/route.ts",
    lineNumber: 1,
    snippet: "export async function POST(req: Request) {\n  const { email, password } = await req.json()",
    remediation: "Implement rate limiting with a library like `@upstash/ratelimit` or `express-rate-limit`. Allow a maximum of 10 attempts per minute per IP.",
    references: ["https://owasp.org/www-community/controls/Blocking_Brute_Force_Attacks"],
    falsePositive: false,
  },
  {
    id: "f-009",
    ruleId: "SEC-012",
    title: "Sensitive data logged to console",
    description: "User passwords and email addresses are being logged to the console, which may appear in log aggregation services and expose PII.",
    severity: "low",
    category: "security",
    filePath: "src/api/auth/register/route.ts",
    lineNumber: 22,
    snippet: 'console.log("Registering user:", { email, password })',
    remediation: "Remove all console.log statements containing PII or credentials. Use a structured logger with appropriate log levels.",
    references: [],
    falsePositive: false,
  },
  {
    id: "f-010",
    ruleId: "DEP-007",
    title: "Outdated dependency: lodash@4.17.20",
    description: "lodash@4.17.20 has 2 known moderate-severity vulnerabilities. Upgrade to 4.17.21 or later.",
    severity: "low",
    category: "dependency",
    filePath: "package.json",
    lineNumber: 31,
    snippet: '"lodash": "^4.17.20"',
    remediation: "Run `npm install lodash@latest` to upgrade to the patched version.",
    references: ["https://www.npmjs.com/advisories/1523"],
    falsePositive: false,
  },
  {
    id: "f-011",
    ruleId: "CFG-009",
    title: "Content-Security-Policy header not set",
    description: "No CSP header is configured. This leaves the application vulnerable to cross-site scripting (XSS) attacks that inject malicious scripts.",
    severity: "low",
    category: "configuration",
    filePath: "next.config.ts",
    lineNumber: 1,
    snippet: "const nextConfig: NextConfig = {};",
    remediation: "Add a Content-Security-Policy header via Next.js `headers()` config or a middleware function.",
    references: ["https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP"],
    falsePositive: false,
  },
  {
    id: "f-012",
    ruleId: "INFO-001",
    title: "TODO comment references unimplemented auth check",
    description: "A TODO comment indicates an authentication check was intentionally skipped during development and never completed.",
    severity: "info",
    category: "security",
    filePath: "src/api/reports/route.ts",
    lineNumber: 7,
    snippet: "// TODO: add auth check before returning reports",
    remediation: "Implement the missing authentication check before this endpoint goes to production.",
    references: [],
    falsePositive: false,
  },
];

export const MOCK_SCORE: DeployScore = {
  overall: 61,
  security: 44,
  performance: 72,
  reliability: 80,
  compliance: 65,
  recommendation: "review",
};

export const MOCK_SUMMARY: ScanSummary = {
  total: 12,
  critical: 1,
  high: 3,
  medium: 4,
  low: 3,
  info: 1,
  passed: 0,
  failed: 12,
};

export const MOCK_SCAN_RESULT: ScanResult = {
  id: "scan_01HZQK3X8MTWP4RJVC6B9NDFE",
  targetId: "proj_01HZQ",
  status: "completed",
  startedAt: "2026-04-28T14:32:01Z",
  completedAt: "2026-04-28T14:32:18Z",
  score: MOCK_SCORE,
  findings: MOCK_FINDINGS,
  summary: MOCK_SUMMARY,
};

export const MOCK_RECENT_SCANS = [
  {
    id: "scan_01HZQK3X8MTWP4RJVC6B9NDFE",
    project: "api-service",
    branch: "main",
    commitSha: "a4f3c91",
    environment: "production",
    score: 61,
    recommendation: "review" as const,
    status: "completed" as const,
    duration: "17s",
    createdAt: "2 minutes ago",
    findings: { critical: 1, high: 3, medium: 4, low: 3, info: 1 },
  },
  {
    id: "scan_01HZPK2W7LSVO3QIUB5A8MCED",
    project: "web-app",
    branch: "feat/auth-refactor",
    commitSha: "2d8e4f1",
    environment: "staging",
    score: 88,
    recommendation: "deploy" as const,
    status: "completed" as const,
    duration: "22s",
    createdAt: "1 hour ago",
    findings: { critical: 0, high: 0, medium: 2, low: 3, info: 4 },
  },
  {
    id: "scan_01HZNJ1V6KRUNT2PHTA7LBCXD",
    project: "api-service",
    branch: "hotfix/session-bug",
    commitSha: "9c1b7a3",
    environment: "production",
    score: 34,
    recommendation: "block" as const,
    status: "completed" as const,
    duration: "14s",
    createdAt: "3 hours ago",
    findings: { critical: 3, high: 2, medium: 1, low: 0, info: 0 },
  },
  {
    id: "scan_01HZMH0U5JQTMS1OGSZK6KAWC",
    project: "worker-service",
    branch: "main",
    commitSha: "5f2a8e9",
    environment: "staging",
    score: 95,
    recommendation: "deploy" as const,
    status: "completed" as const,
    duration: "9s",
    createdAt: "Yesterday",
    findings: { critical: 0, high: 0, medium: 0, low: 1, info: 2 },
  },
  {
    id: "scan_01HZLG9T4IPSLR0NFRYJ5JZVB",
    project: "web-app",
    branch: "main",
    commitSha: "b3d1f72",
    environment: "production",
    score: 79,
    recommendation: "review" as const,
    status: "completed" as const,
    duration: "19s",
    createdAt: "Yesterday",
    findings: { critical: 0, high: 1, medium: 3, low: 2, info: 1 },
  },
];

export const MOCK_DYNAMIC_FINDINGS: DynamicTestEntry[] = [
  {
    id: "dyn-001",
    endpoint: "POST /api/auth/login",
    testType: "Brute Force",
    vulnerable: true,
    severity: "high" as const,
    details: "No rate limiting detected. 500 requests/minute succeeded without throttling.",
    payload: 'POST /api/auth/login\nContent-Type: application/json\n\n{"email":"admin@test.com","password":"[fuzz]"}',
    responseTime: "32ms avg",
  },
  {
    id: "dyn-002",
    endpoint: "GET /api/users?search=",
    testType: "Reflected XSS",
    vulnerable: true,
    severity: "medium" as const,
    details: "Unescaped user input reflected in JSON error response body. Could be exploited in conjunction with a JSONP endpoint.",
    payload: "GET /api/users?search=<script>alert(1)</script>",
    responseTime: "44ms avg",
  },
  {
    id: "dyn-003",
    endpoint: "POST /api/upload",
    testType: "File Upload",
    vulnerable: false,
    severity: "info" as const,
    details: "File type validation and size limits are correctly enforced. PHP and executable files are rejected.",
    payload: "POST /api/upload with Content-Type: application/x-php",
    responseTime: "28ms avg",
  },
  {
    id: "dyn-004",
    endpoint: "GET /api/reports/:id",
    testType: "IDOR",
    vulnerable: true,
    severity: "high" as const,
    details: "Accessing report IDs belonging to other organizations returned data without authorization check.",
    payload: "GET /api/reports/rpt_OTHER_ORG_ID",
    responseTime: "38ms avg",
  },
];
